config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      get 'profile'
      get 'friends'
      get 'accept_invite'
      get 'decline_invite'
    end
    collection do
      get 'reservations'
      get 'schedule'
      post 'grade'
      get 'search'
    end
  end
  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create, :show] do
        member do
          get 'invite'
        end
      end
    end
    collection do
      get 'meals'
      get 'edit_meals'
      get 'search'
    end
    member do
      get 'reservations'
      post 'add_meal'
      post 'delete_meal'
    end
  end

  resources :meals, only: [:index, :new, :create, :destroy, :edit, :update]

  resources :friendships, only: [:destroy] do
    member do
      get 'send_request'
      get 'accept_request'
      get 'decline_request'
    end
  end
  resources :managers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'home#index'

  get 'invitation/:reservation_id/:user_id' => 'invitation#invite'

  get 'test' => 'home#test'
  get 'test2' => 'home#test2'
  post 'tmp' => 'home#tmp', as: 'tmp'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_friendship

  has_many :reservations
  has_many :tables, through: :reservations

  has_many :invitations, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :grades, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, :surname, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if current_user == nil
			@users = User.all
		else
			@users = User.where.not(id: current_user.id)
		end
	end
	def show
		@user = User.find(params[:id])
	end
	def profile
		@user = current_user
		@friends = @user.friends
		@invitations = @user.invitations.includes(:reservation).includes(:user)
		@future_events = Event.joins(:reservation).where("events.user_id = ? and reservations.date >= ?", current_user.id, Date.today)
	end
	def friends

	end
	def reservations
		@user = current_user
		@reservations = @user.reservations
	end
	def accept_invite
		@user = current_user
		@inv = Invitation.find(params[:id])
		
		@event = Event.new
		@event.user_id = current_user.id
		@event.reservation_id = @inv.reservation_id

		if @event.save
			@inv.destroy
		end

		redirect_to action: 'profile'
	end
	def decline_invite

		@inv = Invitation.find(params[:id])
		@inv.destroy

		redirect_to action: 'profile'
	end
	def schedule
		@data = current_user.events.includes(:reservation).includes(:user)
		@past_events = Event.joins(:reservation).where("events.user_id = ? and reservations.date <= ?", current_user.id, Date.today)
		@future_events = Event.joins(:reservation).where("events.user_id = ? and reservations.date >= ?", current_user.id, Date.today)
		#@events.includes(:reservation).includes(:user)

		#Article.includes(:comments).where("articles.published_at <= ? and comments.created_at >= ?", Time.now, Time.now - 1.month).references(:comments)
	end
	def grade
		@grade = Grade.new(grade_params)
		@grade.user_id = current_user.id
		if @grade.save
			redirect_to(:back)
		else
			redirect_to root_path
		end
	end
	def search
		search = params[:search]
		@users = User.where("name LIKE :name or surname LIKE :surname", name: "%#{search}%", surname: "%#{search}%")
	end
	private
	def grade_params
		params.permit(:grade, :event_id)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Users</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Email</th>
							<th>Name</th>
							<th>Surname</th>						
						</thead>
						<tbody>
						<% @users.each_with_index do |us, idx| %>
							<% unless us.admin %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= link_to "#{us.email}", user_path(us) %></td> 
								<td><%= "#{us.name}" %></td>
								<td><%= "#{us.surname}" %></td>
								<% unless !user_signed_in?%>
								<%#<td><%= link_to 'Send request', send_request_friendship_path(us) %>
								<td><%= link_for_user(us) %></td>
								<% end %>
							</tr>
							<% end %>
						<% end %>
						</tbody>
					</table>
		      	</div>
		    </div>
		</div>
	</div>
	<div class="row">
		<%= form_tag search_users_path do %>
		  <p>
		    <%= text_field_tag :search%>
		  </p>
		  <% end %>
	</div>
<div/>

app/views/users/profile.html.erb
<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10"><h1><%= current_user.email %></h1></div>
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Profile</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span><%= current_user.created_at.to_date %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span><%= current_user.last_sign_in_at.to_date %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Name</strong></span><%= current_user.name %></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Surname</strong></span><%= current_user.surname %></li>
          </ul> 
               
       	</div>
    <div class="col-sm-9">
        <div class="panel panel-primary">
            <div class="panel-heading">Future Events</div>
            <div class="panel-body">
            <table class = "table">
            <thead>
              <th>#</th>
              <th>Restaurant</th>
              <th>Reservation for</th>
              <th>Table</th>
              <th>Date</th>
              <th>Time</th>
            </thead>
            <tbody>
            <% @future_events.each_with_index do |data, idx| %>
              <tr>
                <td><%= idx + 1 %></td>
                <td><%= name_for_restaurant(data.reservation.table_id) %></td>
                <td><%= "#{data.reservation.user.name} #{data.reservation.user.surname}" %></td>
                <td><%= "#{data.reservation.table_id}" %></td> 
                <td><%= "#{data.reservation.date}" %></td>
                <td><%= "#{data.reservation.start.strftime('%H:%M')} : #{data.reservation.finish.strftime('%H:%M')}" %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
            </div>
        </div>
    </div>
    </div>

    <div class="row">
  		<div class="col-sm-3"><!--left col-->
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Friends</li>
            <% @friends.each do |friend| %>
	            <li class="list-group-item"><span class="pull-right"><strong><%= button_to "Remove", friendship_path(friend), method: :delete, class: 'btn'%></strong></span><%= link_to "#{friend.name} #{friend.surname}", user_path(friend)%></li>
            <% end %>
          </ul> 
       	</div>

       	  <div class="col-sm-3"><!--left col-->
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Friend requests</li>
            <% current_user.requested_friends.each do |friend| %>
	            <li class="list-group-item">
	            	<span class="pull-right"><strong><%= link_to "Decline", decline_request_friendship_path(friend)%></strong></span>
	            	<span class="pull-right"><strong><%= link_to "Accept", accept_request_friendship_path(friend)%></strong></span>
	            	<%= link_to "#{friend.name} #{friend.surname}", user_path(friend)%>
	           	</li>
            <% end %>
          </ul> 
       	</div>

        <div class="col-sm-6"><!--left col-->
              
            <table class = "table">
              <caption>Invites</caption>
              <thead>
                <th>#</th>
                <th>Friend</th>
                <th>Restaurant</th>
                <th>Date</th>
                <th>Time</th>            
              </thead>
              <tbody>
                <% @invitations.each_with_index do |inv, idx| %>
                  <tr>
                    <% res = reservation(inv.reservation_id) %>
                    <td><%= "#{idx + 1}" %></td>
                    <td><%= "#{inv.reservation.user.name} #{inv.reservation.user.surname}" %></td>
                    <td><%= restaurant_name(inv.reservation_id) %></td>
                    <td><%= "#{res.date}"%></td>
                    <td><%= "#{res.start.strftime('%H:%M')} : #{res.finish.strftime('%H:%M')}"%></td>
                    <td><%= link_to 'Accept', accept_invite_user_path(inv.id) %></td>
                    <td><%= link_to 'Decline', decline_invite_user_path(inv.id) %></td>
                  </tr>
                <% end %>
              </tbody>

            </table>

        </div>
    </div>

</div>

app/views/users/reservations.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">My Reservations</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Restaurant</th>
							<th>Table</th>
							<th>Date</th>
							<th>Time</th>
						</thead>
						<tbody>
						<% @reservations.each_with_index do |res, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= name_for_restaurant(res.table_id) %></td>
								<td><%= "#{res.table_id}" %></td> 
								<td><%= "#{res.date}" %></td>
								<td><%= "#{res.start.strftime('%H:%M')} : #{res.finish.strftime('%H:%M')}" %></td>
								<td><%= link_to 'View', restaurant_table_reservation_path(restaurant_id(res.table_id), res.table_id, res.id) %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		    </div>
		</div>
	</div>
<div/>

app/views/users/schedule.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Future Events</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Restaurant</th>
							<th>Reservation for</th>
							<th>Table</th>
							<th>Date</th>
							<th>Time</th>
						</thead>
						<tbody>
						<% @future_events.each_with_index do |data, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= name_for_restaurant(data.reservation.table_id) %></td>
								<td><%= "#{data.reservation.user.name} #{data.reservation.user.surname}" %></td>
								<td><%= "#{data.reservation.table_id}" %></td> 
								<td><%= "#{data.reservation.date}" %></td>
								<td><%= "#{data.reservation.start.strftime('%H:%M')} : #{data.reservation.finish.strftime('%H:%M')}" %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		    </div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Past Events</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Restaurant</th>
							<th>Reservation for</th>
							<th>Table</th>
							<th>Date</th>
							<th>Time</th>
							<th>Grade</th>
						</thead>
						<tbody>
						<% @past_events.each_with_index do |data, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= name_for_restaurant(data.reservation.table_id) %></td>
								<td><%= "#{data.reservation.user.name} #{data.reservation.user.surname}" %></td>
								<td><%= "#{data.reservation.table_id}" %></td> 
								<td><%= "#{data.reservation.date}" %></td>
								<td><%= "#{data.reservation.start.strftime('%H:%M')} : #{data.reservation.finish.strftime('%H:%M')}" %></td>
								<td>
									<% unless grade_present(current_user, data) %>
										<%= form_tag grade_users_path do %>
										  <p>
										    <%= number_field_tag :grade, in: 1...6 %>
										  </p>
										  <%= hidden_field_tag :event_id, data.id %>
										<% end %>
									<% else %>
										<%= grade(current_user, data) %>
									<% end %>
								</td>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		    </div>
		</div>
	</div>
<div/>

app/views/users/search.html.erb
<%= render partial: 'shared/index_user' %>

app/views/users/show.html.erb
<h1>Hello user</h1>

<%= @user.name %>

<table>
<% @user.requested_friends.each do |friend| %>
	<tr>
		<td><%= "#{friend.name}" %></td>
		<td><%= link_to 'Add', accept_request_friendship_path(friend) %></td>
	</tr>
<% end %>
</table>