config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      get 'profile'
      get 'friends'
      get 'accept_invite'
      get 'decline_invite'
    end
    collection do
      get 'reservations'
      get 'schedule'
      post 'grade'
      get 'search'
    end
  end
  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create, :show] do
        member do
          get 'invite'
        end
      end
    end
    collection do
      get 'meals'
      get 'edit_meals'
      get 'search'
    end
    member do
      get 'reservations'
      post 'add_meal'
      post 'delete_meal'
    end
  end

  resources :meals, only: [:index, :new, :create, :destroy, :edit, :update]

  resources :friendships, only: [:destroy] do
    member do
      get 'send_request'
      get 'accept_request'
      get 'decline_request'
    end
  end
  resources :managers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'home#index'

  get 'invitation/:reservation_id/:user_id' => 'invitation#invite'

  get 'test' => 'home#test'
  get 'test2' => 'home#test2'
  post 'tmp' => 'home#tmp', as: 'tmp'

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
	before_action :authenticate_admin!, except: [:index, :show]

	def index
		@managers = User.where(admin: true)
	end
	def show
		@manager = User.find(params[:id])
	end
	def new
		@manager = User.new
	end
	def create
		@manager = User.new(manager_params)
		@manager.admin = true
		@manager.skip_confirmation!
		if @manager.save
			redirect_to action: 'index'
		else
			redirect_to action: 'new'
		end
	end
	def edit
		@manager = User.find(params[:id])
	end
	def update
		@manager = User.find(params[:id])
		if @manager.update(manager_params)
			redirect_to @manager
		else
			redirect_to action: 'edit'
		end
	end
	def destroy
		@manager = User.find(params[:id])
		@manager.destroy
		redirect_to action: 'index'
	end
	private
	def manager_params
		params.require(:manager).permit(:email, :name, :surname, :password)
	end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/edit.html.erb
<div class="container">
<h1>Edit Manager</h1>

<%= form_for :manager, url: manager_path(@manager), method: :patch do |f| %>

  <div class = "form-group">
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  </div>

  <div class = "form-group">
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  </div>

  <div class = "form-group">
  <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </p>
  </div>

  <div class = "form-group">
  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>
  </div>
  
  <div class = "form-group">
  <p>
    <%= f.submit 'Save', class: "btn" %>
  </p>
  </div>

<% end %>
</div>

app/views/managers/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Managers</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Name</th>
							<th>Surname</th>
							<th>Email</th>
						</thead>
						<tbody>
						<% @managers.each_with_index do |man, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= "#{man.name}" %></td> 
								<td><%= "#{man.surname}" %></td>
								<td><%= link_to "#{man.email}", manager_path(man) %></td>
								<td><%= link_to 'Edit', edit_manager_path(man) %> </td>
								<td><%= button_to 'Delete', manager_path(man), method: :delete, class: 'btn' %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		      	<%= link_to 'Add manager', new_manager_path, class: "btn btn-info"%>
		    </div>
		</div>
	</div>
<div/>

app/views/managers/new.html.erb
<div class="container">
<h1>New Manager</h1>

<%= form_for :manager, url: managers_path do |f| %>

  <div class = "form-group">
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  </div>

  <div class = "form-group">
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  </div>

  <div class = "form-group">
  <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </p>
  </div>

  <div class = "form-group">
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  </div>
  
  <div class = "form-group">
  <p>
    <%= f.submit 'Save', class: "btn" %>
  </p>
  </div>

<% end %>
</div>

app/views/managers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4 col-md-4 user-details">
            <div>
                <div class="container">
                    <h3>Details:</h3>
                    <span class="help-block"><%= "manager id: #{@manager.id}"%></span>
                </div>
                <div class="container">
                    <div class="tab-content">
                        <div id="information" class="tab-pane active">
                            <p><strong>Name: </strong><%= "#{@manager.name}"%></p>
                            <p><strong>Surname: </strong><%= "#{@manager.surname}"%></p>
                            <p><strong>Email: </strong><%= "#{@manager.email}"%></p>
                            <p><strong>Working since: </strong><%= "#{@manager.created_at.to_date}"%></p>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div id="information" class="tab-pane active">
                        <h4>Restaurants</h4>
                    </div>
                    <%= link_to 'Edit', edit_manager_path(@manager) %>
                </div>
            </div>
        </div>
	</div>
</div>