config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      get 'profile'
      get 'friends'
      get 'accept_invite'
      get 'decline_invite'
    end
    collection do
      get 'reservations'
      get 'schedule'
      post 'grade'
      get 'search'
    end
  end
  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create, :show] do
        member do
          get 'invite'
        end
      end
    end
    collection do
      get 'meals'
      get 'edit_meals'
      get 'search'
    end
    member do
      get 'reservations'
      post 'add_meal'
      post 'delete_meal'
    end
  end

  resources :meals, only: [:index, :new, :create, :destroy, :edit, :update]

  resources :friendships, only: [:destroy] do
    member do
      get 'send_request'
      get 'accept_request'
      get 'decline_request'
    end
  end
  resources :managers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'home#index'

  get 'invitation/:reservation_id/:user_id' => 'invitation#invite'

  get 'test' => 'home#test'
  get 'test2' => 'home#test2'
  post 'tmp' => 'home#tmp', as: 'tmp'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :tables, dependent: :destroy
	has_and_belongs_to_many :meals

	validates :name, :description, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :authenticate_managers, except: [:index, :show, :meals, :search]

	def index
		@rests = Restaurant.all
	end
	def show
		@rest = Restaurant.find(params[:id])
		@tables = @rest.tables
	end
	def new
		@restaurant = Restaurant.new
	end
	def create
		@rest = Restaurant.new(restaurant_params)

		if @rest.save
			redirect_to @rest
		else
			redirect_to new_restaurant_path
		end
	end
	def edit
		@restaurant = Restaurant.find(params[:id])
	end
	def update
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update(restaurant_params)
			redirect_to @rest
		else
			render 'edit'
		end
	end
	def destroy
		@rest = Restaurant.find(params[:id])

		if @rest.destroy
			redirect_to restaurants_path
		else
			redirect_to @rest
		end
	end

	def reservations
		@rest = Restaurant.find(params[:id])
		@tables = @rest.tables
	end
	def meals
		@rest = Restaurant.find(params[:format])
		@meals = @rest.meals
	end
	def edit_meals
		@rest = Restaurant.find(params[:format])
		@meals = Meal.all
	end
	def add_meal
		@rest = Restaurant.find(params[:id])
		@meal = Meal.find(params[:format])

		@rest.meals.push(@meal)

		redirect_to(:back)

	end
	def delete_meal
		@rest = Restaurant.find(params[:id])
		@meal = Meal.find(params[:format])

		@rest.meals.delete(@meal)

		redirect_to(:back)
	end
	def search
		search = params[:search]
		@rests = Restaurant.where("name LIKE :name or description LIKE :description", name: "%#{search}%", description: "%#{search}%")
	end
	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :description)
	end
	private
	def authenticate_managers

		if !admin_signed_in?
			if user_signed_in?
				unless current_user.admin 
					redirect_to root_path
				end
			else
				redirect_to root_path
			end
		end

	end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/edit.html.erb
<div class = "container">
<h1> Edit Restaurant </h1>

<%=  form_for :restaurant, url: restaurant_path(@restaurant), method: :patch do |f| %>
  
  <div class="form-group">
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  </div>
 
  <div class="form-group">
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  </div>
  
  <div class="form-group">
  <p>
    <%= f.submit 'Edit', class: 'btn' %>
  </p>
  </div>

<% end %>
</div>

app/views/restaurants/edit_meals.html.erb
<div class="container">
	<h1>Edit menu for restaurant <%= "#{@rest.name}" %></h1>
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Meals</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Name</th>
							<th>Description</th>
							<th>Price</th>
						</thead>
						<tbody>
						<% @meals.each_with_index do |meal, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= "#{meal.name}" %></td> 
								<td><%= "#{meal.description}" %></td>
								<td><%= "#{meal.price}" %></td>
								<% if manager_signed_in %>
									<td><%= add_or_delete_meal(@rest, meal) %></td>
								<% end %>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		    </div>
		</div>
	</div>
<div/>

app/views/restaurants/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Restaurants</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Name</th>
							<th>Description</th>
							<th>Meals</th>
							<th>Average Grade</th>
						</thead>
						<tbody>
						<% @rests.each_with_index do |rest, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= link_to "#{rest.name}", restaurant_path(rest) %></td> 
								<td><%= "#{rest.description}" %></td>
								<td><%= link_to 'Meals', meals_restaurants_path(rest) %>
								<td><%= grade_for_restaurant(rest) %></td>
								<td><%= restaurant_reservations(rest)%></td>
								<% if manager_signed_in %>
								<td><%= link_to 'Edit', edit_restaurant_path(rest) %></td>
								<td><%= button_to 'Delete', restaurant_path(rest), method: :delete, class: 'btn' %></td>
								<% end %>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		      	<% if user_signed_in? %>
			      	<% unless !current_user.admin %>
			      		<%= link_to 'Add restaurant', new_restaurant_path, class: "btn btn-info"%>
			      	<% end %>
		      	<% end %>
		    </div>
		</div>
	</div>
<div/>

app/views/restaurants/meals.html.erb
<div class="container">
	<h1>Restaurant <%= "#{@rest.name}" %></h1>
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Menu</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Name</th>
							<th>Description</th>
							<th>Price</th>
						</thead>
						<tbody>
						<% @meals.each_with_index do |meal, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= "#{meal.name}" %></td> 
								<td><%= "#{meal.description}" %></td>
								<td><%= "#{meal.price}" %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		      	<% if manager_signed_in %>
					<td><%= link_to 'Edit Menu', edit_meals_restaurants_path(@rest) %></td>
				<% end %>
		    </div>
		</div>
	</div>
<div/>

app/views/restaurants/new.html.erb
<div class = "container">
<h1> New Restaurant </h1>

<%= form_for :restaurant, url: restaurants_path do |f| %>

  <div class="form-group">
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
  </div>
  <div class="form-group">
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>
  </div>
  <div class="form-group">
    <p>
      <%= f.submit 'Save', class: "btn" %>
    </p>
  </div>
<% end %>
</div>

app/views/restaurants/reservations.html.erb
<div class="container">
	<h1> Restaurant <%= "#{@rest.name}" %> </h1>
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Reservations</div>
		      	<div class="panel-body">
		      		<% @tables.each do |table| %>
		    		<table class = "table">
		    			<caption class = "text-left"><%= "Table #{table.id}"%></caption>
						<thead>
							<th>#</th>
							<th>User</th>
							<th>Date</th>
							<th>Time</th>
						</thead>
						<tbody>
						<% table.reservations.each_with_index do |res, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= name_for_user(res.user_id) %></td> 
								<td><%= "#{res.date}" %></td>
								<td><%= "#{res.start.strftime('%H:%M')} : #{res.finish.strftime('%H:%M')}" %></td>
							</tr>
						<% end %>
						</tbody>
					</table>
					<% end %>
		      	</div>
		    </div>
		</div>
	</div>
<div/>

app/views/restaurants/search.html.erb
<%= render partial: 'shared/index_restaurant' %>

app/views/restaurants/show.html.erb
<div class="container">
<h1> <%= "#{@rest.name}" %> </h1>

<h3><small> <%= "#{@rest.description}" %> </small></h3>

<div class="col-sm-10">
<div class="panel panel-primary">
   	<div class="panel-heading">Restaurant</div>
	   	<div class="panel-body">
	   		<table class = "table">
				<thead>
					<th>#</th>
					<th>Table ID</th>
					<th>No. seats</th>
				</thead>
				<tbody>
					<% @tables.each_with_index do |table, idx| %>
						<tr>
							<td><%= idx + 1 %></td>
							<td><%= "#{table.id}" %></td> 
							<td><%= "#{table.noseats}" %></td>
							<%#<td><%= link_to 'Edit', edit_restaurant_path(rest) </td>
							<td><%= button_to 'Delete', restaurant_path(rest), method: :delete </td>%>
							<% if !manager_signed_in %>
							<td><%= add_reservation(@rest, table) %></td>
							<% end %>
							<td><%= reservations_for_table(@rest, table) %></td>
							<td><%= link_for_destroy_table(@rest, table) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<% if manager_signed_in %>
		<%#= link_for_adding_tables(@rest) %>
		<%= link_to 'Add Table',  new_restaurant_table_path(@rest), class: 'btn btn-info'%>
		<% end %>
    </div>
   	</div>

</div>