config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      get 'profile'
      get 'friends'
      get 'accept_invite'
      get 'decline_invite'
    end
    collection do
      get 'reservations'
      get 'schedule'
      post 'grade'
      get 'search'
    end
  end
  resources :restaurants do
    resources :tables do
      resources :reservations, only: [:index, :new, :create, :show] do
        member do
          get 'invite'
        end
      end
    end
    collection do
      get 'meals'
      get 'edit_meals'
      get 'search'
    end
    member do
      get 'reservations'
      post 'add_meal'
      post 'delete_meal'
    end
  end

  resources :meals, only: [:index, :new, :create, :destroy, :edit, :update]

  resources :friendships, only: [:destroy] do
    member do
      get 'send_request'
      get 'accept_request'
      get 'decline_request'
    end
  end
  resources :managers, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'home#index'

  get 'invitation/:reservation_id/:user_id' => 'invitation#invite'

  get 'test' => 'home#test'
  get 'test2' => 'home#test2'
  post 'tmp' => 'home#tmp', as: 'tmp'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, 
  		:rememberable, :trackable, :validatable,
  		:authentication_keys => [:username]
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	belongs_to :reservation

	has_many :grades, dependent: :destroy

	validates_uniqueness_of :user, :scope => [:reservation]
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	belongs_to :event
	belongs_to :user

	validates :grade, presence: true
	validates_uniqueness_of :user, :scope => [:event]
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :reservation
	belongs_to :user

	validates_uniqueness_of :user, :scope => [:reservation]
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	has_and_belongs_to_many :restaurants

	validates :name, :description, :price, presence: true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :table

	has_many :invitations, dependent: :destroy
	has_many :events, dependent: :destroy

	validates :date, :start, :finish, presence: true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :tables, dependent: :destroy
	has_and_belongs_to_many :meals

	validates :name, :description, presence: true
end

app/models/table.rb
class Table < ActiveRecord::Base
	belongs_to :restaurant

	has_many :reservations, dependent: :destroy
	has_many :users, through: :reservations

	validates :noseats, :restaurant_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_friendship

  has_many :reservations
  has_many :tables, through: :reservations

  has_many :invitations, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :grades, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, :surname, presence: true

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	def test
		admin = Admin.new
		admin.id = 1
		admin.email = 'sys@admin.com'
		admin.password = 'password'
		admin.username = 'sys'
		admin.save
		render 'index'
	end
	def test2
		@time1 = Time.now
		@time2 = Time.now-4.minutes
		@difference = TimeDifference.between(@time2, @time1).in_minutes
		@test = (TimeDifference.between(@time2, @time1).in_minutes < 30 and @time1 < @time2)
	end
	def tmp
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_for_user user
		if !current_user.admin
			if current_user.friends_with?(user)
				button_to 'Remove friend', friendship_path(user), method: :delete, class: 'btn'
			else
				link_to 'Send request', send_request_friendship_path(user)
			end
		end
	end

	def name_for_user id
		user = User.find(id)
		user.name + " " + user.surname
	end

	def link_for_user_reservations
		if user_signed_in?
			if !current_user.admin
				link_to 'My Reservations', reservations_users_path
			end
		end
	end

	def link_for_user_schedule
		if user_signed_in?
			if !current_user.admin
				link_to 'Timeline', schedule_users_path
			end
		end
	end

	def name_for_restaurant id
		table = Table.find(id)
		restaurant = Restaurant.find(table.restaurant_id)
		restaurant.name
	end

	def link_for_adding_tables rest
		if admin_signed_in?
			link_to 'Add Table',  new_restaurant_table_path(rest)
		else
			if user_signed_in?
				if current_user.admin
					link_to 'Add Table',  new_restaurant_table_path(rest)
				end
			end
		end
	end

	def manager_signed_in
		if admin_signed_in?
			return true
		else
			if user_signed_in?
				if current_user.admin
					return true
				end
			end
		end

	end

	def restaurant_id table
		table = Table.find(table)
		table.restaurant_id
	end

	def table_id reservation
		reservation = Reservation.find(reservation)
		reservation.table_id
	end

	def restaurant_name reservation
		reservation = Reservation.find(reservation)
		table = Table.find(reservation.table_id)
		restaurant = Restaurant.find(table.restaurant_id)
		restaurant.name
	end

	def reservation reservation
		reservation = Reservation.find(reservation)
		reservation
	end

	def add_reservation restaurant, table
		if user_signed_in?
			if !current_user.admin
				link_to 'Add Reservation', new_restaurant_table_reservation_path(restaurant, table)
			end
		end
	end

	def link_for_destroy_table restaurant, table
		if admin_signed_in?
			button_to 'Delete', restaurant_table_path(restaurant, table), method: :delete, class: 'btn'
		else
			if user_signed_in?
				if current_user.admin
					button_to 'Delete', restaurant_table_path(restaurant, table), method: :delete, class: 'btn'
				end
			end
		end
	end

	def reservations_for_table restaurant, table
		if admin_signed_in?
			link_to 'See Reservations', restaurant_table_reservations_path(restaurant, table)
		else
			if user_signed_in?
				if current_user.admin
					link_to 'See Reservations', restaurant_table_reservations_path(restaurant, table)
				end
			end
		end
	end

	def restaurant_reservations restaurant
		if admin_signed_in?
			link_to 'See Reservations', reservations_restaurant_path(restaurant)
		else
			if user_signed_in?
				if current_user.admin
					link_to 'See Reservations', reservations_restaurant_path(restaurant)
				end
			end
		end
	end

	def grade_present user, event
		Grade.exists?(user_id: user, event_id: event)
	end

	def grade user, event
		Grade.where(user_id: user, event_id: event).first.grade
	end

	def grade_for_restaurant rest
		sql = "SELECT restaurants.name, tables.id, reservations.id, events.id, grades.id, grades.grade
				FROM restaurants
				INNER JOIN tables
				ON restaurants.id = tables.restaurant_id
				and restaurants.id = " + rest.id.to_s + "
				INNER JOIN reservations
				ON reservations.table_id = tables.id
				INNER JOIN events
				ON events.reservation_id = reservations.id
				INNER JOIN grades
				ON grades.event_id = events.id;"
		records_array = ActiveRecord::Base.connection.execute(sql)
		#avg = 0
		#unless grades.size == 0
		#	grades.each do |grade|
		#		avg = avg + grade.grade
		#	end
		#	avg = avg / grades.size
		#end
		#avg
		records_array.size
	end
	def add_or_delete_meal rest, meal
		unless rest.meals.include?(meal)
			button_to 'Add Meal', add_meal_restaurant_path(@rest, meal), method: :post, class: 'btn'
		else
			button_to 'Delete Meal', delete_meal_restaurant_path(@rest, meal), method: :post, class: 'btn'
		end
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IsaProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '**defaults**', 'data-turbolinks-track' => true %>
  <%# javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if admin_signed_in? %>
	<%= render partial: 'shared/admin_navbar' %>
<% else %>
	<%= render partial: 'shared/navbar' %>
<% end %>

<div class="container">
	<% if notice %><div class="alert alert-info"><%= notice %></div>
	<% end %>
	<% if alert %><div class="alert alert-warning"><%= alert %></div>
	<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav">
      <li><%= link_to 'Restaurants', restaurants_path%></li>
      <li><%= link_to 'Managers', managers_path%></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
		  <li><%= button_to 'Logout', destroy_admin_session_path, method: :delete, class: 'btn' %></li>
    </ul>

  </div>
</nav>

app/views/shared/_index_restaurant.html.erb
<div class="container">

	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Restaurants</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Name</th>
							<th>Description</th>
							<th>Meals</th>
							<th>Average Grade</th>
						</thead>
						<tbody>
						<% @rests.each_with_index do |rest, idx| %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= link_to "#{rest.name}", restaurant_path(rest) %></td> 
								<td><%= "#{rest.description}" %></td>
								<td><%= link_to 'Meals', meals_restaurants_path(rest) %>
								<td><%= grade_for_restaurant(rest) %></td>
								<td><%= restaurant_reservations(rest)%></td>
								<% if manager_signed_in %>
								<td><%= link_to 'Edit', edit_restaurant_path(rest) %></td>
								<td><%= button_to 'Delete', restaurant_path(rest), method: :delete, class: 'btn' %></td>
								<% end %>
							</tr>
						<% end %>
						</tbody>
					</table>
		      	</div>
		      	<% if manager_signed_in %>
			      	<%= link_to 'Add restaurant', new_restaurant_path, class: "btn btn-info"%>
		      	<% end %>
		    </div>
		</div>
	</div>
	<div class="row">
		<%= form_tag search_restaurants_path, method: 'get' do %>
		  <p>
		    <%= text_field_tag :search%>
		  </p>
		  <% end %>
	</div>
<div/>

app/views/shared/_index_user.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-10">
		    <div class="panel panel-primary">
		      	<div class="panel-heading">Users</div>
		      	<div class="panel-body">
		    		<table class = "table">
						<thead>
							<th>#</th>
							<th>Email</th>
							<th>Name</th>
							<th>Surname</th>						
						</thead>
						<tbody>
						<% @users.each_with_index do |us, idx| %>
							<% unless us.admin %>
							<tr>
								<td><%= idx + 1 %></td>
								<td><%= link_to "#{us.email}", user_path(us) %></td> 
								<td><%= "#{us.name}" %></td>
								<td><%= "#{us.surname}" %></td>
								<% unless !user_signed_in?%>
								<%#<td><%= link_to 'Send request', send_request_friendship_path(us) %>
								<td><%= link_for_user(us) %></td>
								<% end %>
							</tr>
							<% end %>
						<% end %>
						</tbody>
					</table>
		      	</div>
		    </div>
		</div>
	</div>
	<div class="row">
		<%= form_tag search_users_path, method: 'get' do %>
		  <p>
		    <%= text_field_tag :search%>
		  </p>
		  <% end %>
	</div>
<div/>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav">
      <li><%= link_to 'Restaurants', restaurants_path%></li>
      <li><%= link_to 'Users', users_path%></li>
      <li><%= link_for_user_reservations %></li>
      <li><%= link_for_user_schedule %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
      	<li><%= link_to current_user.email, profile_user_path(current_user) %></li>
		    <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn' %></li>
	  <% else %>
	    <li><%= link_to 'Sign in', new_user_session_path %></li>
	    <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>

  </div>
</nav>